### ISSUE TITLE
使用=给包含二级属性的vm赋值导致的一些$watch问题

### ISSUE THREAD

**Issue by fanliao** [RubyLouvre/avalon#1109]
Chrome:  42.0.2311.152 (64-bit)

### avalon 1.4.6和1.4.7下的问题
avalon js: 1.46 built in 2015.9.18

测试代码：
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        <script src="../avalon.js" ></script>
        <script>
            var model = avalon.define({
                $id: "test",
                aaa: {b:"2"},
            })
	    avalon.log("add watch");
            model.aaa.$watch("b", function(a, b) {
                console.log("aaa.b is ", a, b)
            })
			
	    //avalon.mix(model.aaa, {b:"3", c:1})
	    model.aaa = {b:"3", c:1}
        </script>
    </head>
    <body ms-controller="test" class='ms-hover'>
		<input type="text" ms-duplex-string="aaa.b"></input>
    </body>
</html>
```

测试结果：
* 改变输入框的内容，没有看见log
* 如果使用被注释掉的avalon.mix来赋值，那么就可以看到log，但子属性c没有绑定上去

### avalon 1.5.4下运行结果正常，但会在console中看到warn

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        <script src="../avalon.js" ></script>
        <script>
            var model = avalon.define({
                $id: "test",
                aaa: {b:"2"},
            })
            model.$watch("aaa.b", function(a, b) {
                console.log("aaa.b is ", a, b)
            })
			
	   model.aaa = {b:"3", c:1}
        </script>
    </head>
    <body ms-controller="test" class='ms-hover'>
		<input type="text" ms-duplex-string="aaa.b"></input>
    </body>
</html>
```

测试结果：
在输入框中输入内容后，能在console中看到相应的log，但也看到有warning消息出现：
```
warning:exception throwed in [avalon.injectBinding]  ReferenceError: element is not defined {stack: (...), message: "element is not defined"}

"ReferenceError: element is not defined
    at Object.avalon.directive.update [as handler] (file:///D:/develop/packages/avalon-1.5.4/avalon.js:4020:34)
    at Object.avalon.injectBinding.binding.update (file:///D:/develop/packages/avalon-1.5.4/avalon.js:1811:25)
    at Object.Buffer.flush (file:///D:/develop/packages/avalon-1.5.4/avalon.js:3357:31)
    at Array.<anonymous> (file:///D:/develop/packages/avalon-1.5.4/avalon.js:3351:20)
    at MutationObserver.callback (file:///D:/develop/packages/avalon-1.5.4/avalon.js:124:21)"
```

**Comment by RubyLouvre** [comment]
1.5.4 已经修复 https://github.com/RubyLouvre/avalon2/commit/e36232137a63724acb4b8c197f6e00d946e36e9d

待会看一下1.4.7

**Comment by RubyLouvre** [comment]
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        <script src="avalon.js" ></script>
        <script>
            var model = avalon.define({
                $id: "test",
                aaa: {b: "2"},
            })
            avalon.log("add watch");
            model.aaa.$watch("b", function (a, b) {
                console.log(avalon.version)
                console.log("aaa.b is ", a, b)
            })

            //avalon.mix(model.aaa, {b:"3", c:1})
            model.aaa = {b: "3", c: 1}
        </script>
    </head>
    <body ms-controller="test" class='ms-hover'>
        <input type="text" ms-duplex-string="aaa.b"></input>
    </body>
</html>
```
