### ISSUE TITLE
[Bug Report]: 整个对象绑定时，如果内层对象被置空会报错（1.5.4）

### ISSUE THREAD

**Issue by fish-ball** [RubyLouvre/avalon#1119]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src="js/avalonjs/avalon.modern.min.js"></script>
</head>
<body ms-controller="main">

    <div ms-if="outer.inner">
        {{ outer.inner.name }}
    </div>
    <a href="javascript:;" ms-click="reset">reset</a>

    <script>
        var vm = avalon.define({
            $id: 'main',
            outer: {},
            reset: function() {
                vm.outer = {};
            }
        });
        vm.outer = {
            inner: {
                name: 'Hello world!'
            }
        };
    </script>

</body>
</html>
```

点击 reset 按钮时，会报错：

```
warning:exception throwed in [avalon.injectBinding]  TypeError: Cannot read property 'name' of undefined
    at Number.eval (eval at i (http://cps.easecloud.cn/js/avalonjs/avalon.modern.min.js:1:407), <anonymous>:3:20)
    at Object.avalon.injectBinding.e.update (http://cps.easecloud.cn/js/avalonjs/avalon.modern.min.js:1:27889)
    at Object.pa.flush (http://cps.easecloud.cn/js/avalonjs/avalon.modern.min.js:2:5179)
    at Array.<anonymous> (http://cps.easecloud.cn/js/avalonjs/avalon.modern.min.js:2:5105)
    at MutationObserver.t (http://cps.easecloud.cn/js/avalonjs/avalon.modern.min.js:1:19628)
```

**Comment by fish-ball** [comment]
注意关键问题在于，初始化的时候 outer 就是 {}，也没有出问题，但是如果有了 inner 再变成没有，就会出现问题了。感觉是在对象绑定的时候，缺少了一步先遍历旧 object 的子对象属性然后将其从底到顶置空以触发绑定的问题。

**Comment by RubyLouvre** [comment]
这是警告吧

**Comment by RubyLouvre** [comment]
不是错误
