### ISSUE TITLE
require的baseUrl与a.b.c()得到的地址格式不同，前者如果没有协议就对比不上了

### ISSUE THREAD

**Issue by mougeli** [RubyLouvre/avalon#1374]
> avalon.js
> 当baseUrl没有协议前缀的时候，就永远require完不成了。
```javascript
// 生成ID时候的代码
if (id.indexOf(this.res + "!") === 0) {
    id = id.slice(this.res.length + 1) //处理define("css!style",[], function(){})的情况
}
var url = id
//1. 是否命中paths配置项
var usePath = 0
var baseUrl = this.baseUrl
var rootUrl = this.parentUrl || baseUrl
eachIndexArray(id, kernel.paths, function(value, key) {
    url = url.replace(key, value)
    usePath = 1
})
// 加载后的代码
if (stack) {
    /**e.stack最后一行在所有支持的浏览器大致如下:
     *chrome23:
     * at http://113.93.50.63/data.js:4:1
     *firefox17:
     *@http://113.93.50.63/query.js:4
     *opera12:http://www.oldapps.com/opera.php?system=Windows_XP
     *@http://113.93.50.63/data.js:4
     *IE10:
     *  at Global code (http://113.93.50.63/data.js:4:1)
     *  //firefox4+ 可以用document.currentScript
     */
    stack = stack.split(/[@ ]/g).pop() //取得最后一行,最后一个空格或@之后的部分
    stack = stack[0] === "(" ? stack.slice(1, -1) : stack.replace(/\s/,
        "") //去掉换行符
    return trimQuery(stack.replace(/(:\d+)?:\d+$/i, "")) //去掉行号与或许存在的出错字符起始位置
}
````

**Comment by RubyLouvre** [comment]
那自己重置一下baseUrl，或者使用alias为你模块指定完整的路径
