### ISSUE TITLE
请教: select联动在有父级ms-controller时无效

### ISSUE THREAD

**Issue by rubyisapm** [RubyLouvre/avalon#1673]
http://www.cnblogs.com/rubylouvre/p/5618007.html

我使用的是最后一个例子，如果在linkage外层再套一层ms-controller，则联动无效。

```

<div ms-controller="list">
    <div ms-controller="linkage">
        <h3>下拉框三级联动</h3>
        <select ms-duplex="@firstSelected" >
            <option  ms-for="el in @first" ms-attr="{value:el}" >{{el}}</option>
        </select>
        <select ms-duplex="@secondSelected" >
            <option  ms-for="el in @second" ms-attr="{value:el}" >{{el}}</option>
        </select>
        <select ms-duplex="@thirdSelected" >
            <option  ms-for="el in @third" ms-attr="{value:el}" >{{el}}</option>
        </select>
    </div>
</div>
```
望老师指点.

**Comment by RubyLouvre** [comment]
再套一个，必须再定义一个VM啊

**Comment by rubyisapm** [comment]
我定义了list的，最简单的var list=avalon.define({$id:"list"}); 不可以的....

**Comment by RubyLouvre** [comment]
```html

<!DOCTYPE html>
<html>
    <head>
        <script src="../dist/avalon.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <script>
            var map = {
                "中国": ["江南四大才子", "初唐四杰", "战国四君子"],
                "日本": ["日本武将", "日本城堡", "幕府时代"],
                "欧美": ["三大骑士团", "三大魔幻小说", "七大奇迹"],
                "江南四大才子": ["祝枝山", "文征明", "唐伯虎", "周文宾"],
                "初唐四杰": ["王勃", "杨炯", "卢照邻", "骆宾王"],
                "战国四君子": ["楚国春申君黄歇", "齐国孟尝君田文", "赵国平原君赵胜", "魏国信陵君魏无忌"],
                "日本武将": ["织田信长", "德川家康", "丰臣秀吉"],
                "日本城堡": ["安土城", "熊本城", "大坂城", "姬路城"],
                "幕府时代": ["镰仓", "室町", "丰臣", "江户"],
                "三大骑士团": ["圣殿骑士团", "医院骑士团", "条顿骑士团"],
                "三大魔幻小说": ["冰与火之歌", "时光之轮", "荆刺与白骨之王国"],
                "七大奇迹": ["埃及胡夫金字塔", "奥林匹亚宙斯巨像", "阿尔忒弥斯月神殿", "摩索拉斯陵墓", "亚历山大港灯塔", "巴比伦空中花园", "罗德岛太阳神巨像"]
            }
            var vm = avalon.define({
                $id: 'linkage',
                first: ["中国", "日本", "欧美"],
                second: map['日本'].concat(),
                third: map['日本武将'].concat(),
                firstSelected: "日本",
                secondSelected: "日本武将",
                thirdSelected: "织田信长"
            })


            vm.$watch("firstSelected", function (a) {
                vm.second = map[a].concat()
                vm.secondSelected = vm.second[0]
            })
            vm.$watch("secondSelected", function (a) {
                vm.third = map[a].concat()
                vm.thirdSelected = vm.third[0]
            })
            avalon.define({
                $id:'test',
                ddd:222
            })

        </script>
    </head>
    <body ms-controller="test">
        <div ms-controller="linkage">
            <h3>下拉框三级联动</h3>
            <select ms-duplex="@firstSelected" >
                <option  ms-for="el in @first" ms-attr="{value:el}" >{{el}}</option>
            </select>
            <select ms-duplex="@secondSelected" >
                <option  ms-for="el in @second" ms-attr="{value:el}" >{{el}}</option>
            </select>
            <select ms-duplex="@thirdSelected" >
                <option  ms-for="el in @third" ms-attr="{value:el}" >{{el}}</option>
            </select>
        </div>
    </body>
</html>


```

**Comment by RubyLouvre** [comment]
要自己认真一点，不要动不动就问。

【原文】
子曰：“不愤不咎，不悱不发。举一隅不以三隅反，则不复也。”
【译文】
孔子说：“不到他努力想弄明白而不得的程度不要去开导他；不到他心里明白却不能完善表达出来的程度不要去启发他。如果他不能举一反三，就不要再反复地给他举例了。” 

你这样不自己多动脑，一味依赖别人，很难成长的

**Comment by rubyisapm** [comment]
但是这个例子真的运行不起来....

**Comment by RubyLouvre** [comment]
我的为什么能运行呢，你的是什么版本
npm install avalon2

**Comment by rubyisapm** [comment]
avalon版本 2.1.5 浏览器为chrome 51.0.2704.103

**Comment by rubyisapm** [comment]
```
avalon.min.js:1controller SyntaxError: Unexpected identifier(…) SyntaxError: Unexpected identifier
    at Function.a [as render] (http://static.uc108.com/cdn/avalon/2.1.5/avalon.min.js:3:15578)
    at update (http://static.uc108.com/cdn/avalon/2.1.5/avalon.min.js:2:8537)
    at e.exports (http://static.uc108.com/cdn/avalon/2.1.5/avalon.min.js:2:7632)
    at Object.diff (http://static.uc108.com/cdn/avalon/2.1.5/avalon.min.js:2:8345)
    at http://static.uc108.com/cdn/avalon/2.1.5/avalon.min.js:3:20846
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at o (http://static.uc108.com/cdn/avalon/2.1.5/avalon.min.js:3:20768)
    at a (http://static.uc108.com/cdn/avalon/2.1.5/avalon.min.js:3:20496) diffProps error
XHR finished loading: POST "https://www.google-analytics.com/collect".
```
这是报错信息，我用ms-for循环经常有这种报错

**Comment by RubyLouvre** [comment]
升一下吧

**Comment by rubyisapm** [comment]
好的，谢谢
