### ISSUE TITLE
"ms-duplex" error when using in a post append element.

### ISSUE THREAD

**Issue by zvit1** [RubyLouvre/avalon#1973]
Browser: Chrome 57

avalon: v2.2.5

HTML:
```
<body ms-controller="app">
...
</body>
```

Javascript:
```
avalon.define({
  $id: 'app',
  foo: ''
})
$(document.body).append('<input type="text" ms-duplex="@foo" />')
avalon.scan(document.body)
```
Error:(I used webpack, so error is in bundle.js)
```
Uncaught TypeError: Cannot convert undefined or null to object
    at toString (native)
    at Function.eval (eval at ./node_modules/core-js/modules/_ctx.js (http://localhost:3000/bundle.js:988:1), <anonymous>:18:15)
    at RegExp.test (<anonymous>)
    at updateDataEvents (eval at ./node_modules/avalon2/dist/avalon.js (http://localhost:3000/bundle.js:733:1), <anonymous>:6402:48)
    at Action.duplexBind (eval at ./node_modules/avalon2/dist/avalon.js (http://localhost:3000/bundle.js:733:1), <anonymous>:6227:9)
    at Action.update (eval at ./node_modules/avalon2/dist/avalon.js (http://localhost:3000/bundle.js:733:1), <anonymous>:6541:28)
    at eval (eval at ./node_modules/avalon2/dist/avalon.js (http://localhost:3000/bundle.js:733:1), <anonymous>:6975:38)
    at Render.complete (eval at ./node_modules/avalon2/dist/avalon.js (http://localhost:3000/bundle.js:733:1), <anonymous>:7416:17)
    at Render.scanChildren (eval at ./node_modules/avalon2/dist/avalon.js (http://localhost:3000/bundle.js:733:1), <anonymous>:7258:22)
    at Render.init (eval at ./node_modules/avalon2/dist/avalon.js (http://localhost:3000/bundle.js:733:1), <anonymous>:7237:18)
```

Is my method wrong, or avalon doesn't allow post append "ms-duplex"?

**Comment by zvit1** [comment]
When I just write a little demo without webpack, this error doesn't appear, so please ignore this issue until I find the reason.

**Comment by zvit1** [comment]
I didn't find the solution, so I use ms-on-input to avoid this problem.

**Comment by RubyLouvre** [comment]
既然你使用了MVVM，就不应该使用DOM方法，因为avalon会自动扫描页面，你自己扫描时，新加的部分不会添加到原模板中，因此它里面的监听部分没有input这个元素

**Comment by RubyLouvre** [comment]
Since you are using the MVVM, you should not use DOM methods, because of avalon will automatically scan the pages.  when you use **scan** method,  part of the new added does not add to the original template, so it's the listening **input** element
